name: inflearn_code_factory
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.0
  retrofit: '>=4.0.0 <5.0.0'
  logger: ^2.0.2+1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  skeletons: ^0.0.3

flutter:

  uses-material-design: true

  assets:
    - asset/img/food/
    - asset/img/logo/
    - asset/img/misc/
    - asset/rive/
    - asset/svg/icon/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/fonts/NotoSansKR-Thin.otf
          weight: 100
    - family: Pretendard
      fonts:
        - asset: asset/fonts/pretendard/Pretendard-Black.otf
          weight: 900
        - asset: asset/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: asset/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: asset/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: asset/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: asset/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: asset/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: asset/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: asset/fonts/pretendard/Pretendard-Thin.otf
          weight: 100